# name: Lighthouse
# on: [push, pull_request]
# jobs:
#   lighthouse:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "14.x"
#       - run: sleep 30
#       - name: vercel-preview-url
#         uses: zentered/vercel-preview-url@v1.0.0
#         id: vercel_preview_url
#         env:
#           VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
#         with:
#           vercel_team_id: ${{ secrets.VERCEL_TEAM_ID }}
#           vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
#       - name: Get URL
#         run: echo "https://${{ steps.vercel_preview_url.outputs.preview_url }}"
#       - run: yarn install
#         urls: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
#         uploadArtifacts: true
#         temporaryPublicStorage: true
#       - name: run Lighthouse CI
#         run: |
#           yarn global add @lhci/cli@0.8.x
#           lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
#         # We need to integrate https://github.com/zentered/vercel-preview-url to use this build instead of building in this test
  
#         env:
#           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          
#comment